package com.flatcode.littlemovieadmin.Unit;

import com.flatcode.littlemovieadmin.Activity.CastActivity;
import com.flatcode.littlemovieadmin.Activity.CastAddActivity;
import com.flatcode.littlemovieadmin.Activity.CastDetailsActivity;
import com.flatcode.littlemovieadmin.Activity.CastEditActivity;
import com.flatcode.littlemovieadmin.Activity.CastMovieAddActivity;
import com.flatcode.littlemovieadmin.Activity.CategoriesActivity;
import com.flatcode.littlemovieadmin.Activity.CategoryAddActivity;
import com.flatcode.littlemovieadmin.Activity.CategoryDetailsActivity;
import com.flatcode.littlemovieadmin.Activity.CategoryEditActivity;
import com.flatcode.littlemovieadmin.Activity.EditorsChoiceActivity;
import com.flatcode.littlemovieadmin.Activity.EditorsChoiceAddActivity;
import com.flatcode.littlemovieadmin.Activity.FavoritesActivity;
import com.flatcode.littlemovieadmin.Activity.MainActivity;
import com.flatcode.littlemovieadmin.Activity.MovieAddActivity;
import com.flatcode.littlemovieadmin.Activity.MovieDetailsActivity;
import com.flatcode.littlemovieadmin.Activity.MovieEditActivity;
import com.flatcode.littlemovieadmin.Activity.MovieViewActivity;
import com.flatcode.littlemovieadmin.Activity.MoviesActivity;
import com.flatcode.littlemovieadmin.Activity.PrivacyPolicyActivity;
import com.flatcode.littlemovieadmin.Activity.PrivacyPolicyEditActivity;
import com.flatcode.littlemovieadmin.Activity.ProfileActivity;
import com.flatcode.littlemovieadmin.Activity.ProfileEditActivity;
import com.flatcode.littlemovieadmin.Activity.SliderShowActivity;
import com.flatcode.littlemovieadmin.Activity.SplashActivity;
import com.flatcode.littlemovieadmin.Activity.UsersActivity;
import com.flatcode.littlemovieadmin.Auth.ForgetPasswordActivity;
import com.flatcode.littlemovieadmin.Auth.LoginActivity;
import com.flatcode.littlemovieadmin.Service.FloatingWidgetService;

public class CLASS {
    public static Class MAIN = MainActivity.class;
    public static Class SPLASH = SplashActivity.class;
    public static Class LOGIN = LoginActivity.class;
    public static Class FORGET_PASSWORD = ForgetPasswordActivity.class;
    public static Class FAVORITES = FavoritesActivity.class;
    public static Class PRIVACY_POLICY = PrivacyPolicyActivity.class;
    public static Class PRIVACY_POLICY_EDIT = PrivacyPolicyEditActivity.class;
    public static Class EDITORS_CHOICE = EditorsChoiceActivity.class;
    public static Class EDITORS_CHOICE_ADD = EditorsChoiceAddActivity.class;
    public static Class PROFILE = ProfileActivity.class;
    public static Class PROFILE_EDIT = ProfileEditActivity.class;
    public static Class USERS = UsersActivity.class;
    public static Class CATEGORY_ADD = CategoryAddActivity.class;
    public static Class CATEGORY_EDIT = CategoryEditActivity.class;
    public static Class CATEGORIES = CategoriesActivity.class;
    public static Class CATEGORY_DETAILS = CategoryDetailsActivity.class;
    public static Class CAST_ADD = CastAddActivity.class;
    public static Class CAST_EDIT = CastEditActivity.class;
    public static Class CAST = CastActivity.class;
    public static Class CAST_DETAILS = CastDetailsActivity.class;
    public static Class SLIDER_SHOW = SliderShowActivity.class;
    public static Class MOVIE_ADD = MovieAddActivity.class;
    public static Class MOVIE_EDIT = MovieEditActivity.class;
    public static Class MOVIE_DETAILS = MovieDetailsActivity.class;
    public static Class MOVIES = MoviesActivity.class;
    public static Class MOVIE_VIEW = MovieViewActivity.class;
    public static Class CAST_MOVIE = CastMovieAddActivity.class;
    public static Class SERVICE = FloatingWidgetService.class;
}